name: atlas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_auth: ^4.17.4
  flutter:
    sdk: flutter
  json_theme: ^6.4.0
  flutter_spinkit: ^5.2.0
  provider: ^6.1.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  uuid: ^4.3.3
  flutter_dotenv: ^5.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/appainter_theme.json
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_icons:
  image_path: "icon/icon.png" 
  android: true
  ios: true
  remove_alpha_ios: true